---
namespace: "pureport"
name: "pureport"
description: A collection of Ansible Modules & Roles for the Pureport ReST API.
version: "0.10.0"
readme: "README.md"
authors:
  - "Matt Traynham <matt.traynham@pureport.com>"
dependencies:
license: "GPL-3.0-only"
tags:
  - networking
  - multicloud
  - cloud
  - aws
  - azure
  - google
  - vpn
  - pureport
  - web
  - sdn
  - bgp
  - nat
repository: "https://github.com/ansible-collections/pureport"
documentation: "https://github.com/ansible-collections/pureport/blob/develop/README.md"
homepage: "https://www.pureport.com/"
issues: "https://github.com/ansible-collections/pureport/issues"
build_ignore:
  - test
  - examples/group_vars
