---
namespace: "pureport"
name: "pureport"
version: "0.0.7"
readme: "README.md"
authors:
  - "Matt Traynham <matt.traynham@pureport.com>"
dependencies:
license: "GPL-3.0-only"
tags:
  - networking
  - multicloud
  - cloud
  - aws
  - azure
  - google
  - vpn
  - pureport
  - web
  - sdn
  - bgp
  - nat
repository: "https://www.github.com/pureport/pureport-ansible-modules"
documentation: "https://github.com/pureport/pureport-ansible-modules/blob/develop/README.md"
homepage: "https://www.pureport.com/"
issues: "https://www.github.com/pureport/pureport-ansible-modules/issues"
