---
- hosts: localhost
  vars:
    ansible_python_interpreter: "./venv/bin/python"  # Required for virtualenv...
  collections:
    - pureport.pureport_ansible_modules
  roles:
    - role: aws
      aws_region: us-west-2
      aws_vpc_name: Ansible-VPC
      aws_vpc_cidr_block: 10.0.0.0/24
      aws_vpc_subnet_cidr: 10.0.0.0/24
      aws_vgw_name: Ansible-VGW
      aws_vpc_route_table_name: Ansible-RouteTable
      aws_direct_connect_gateway_name: Ansible-Gateway
      aws_direct_connect_virtual_interface_name: Ansible-VIF
      pureport_connection_name: My AWS Private Connection
      pureport_connection_speed: 50
      pureport_connection_high_availability: true
      pureport_connection_location_href: /locations/us-sea
      pureport_connection_peering_type: PRIVATE
      pureport_connection_billing_term: HOURLY
    - role: aws
      aws_region: us-west-2
      aws_direct_connect_virtual_interface_name: Ansible-Public-VIF
      pureport_connection_name: My AWS Public Connection
      pureport_connection_speed: 50
      pureport_connection_high_availability: true
      pureport_connection_location_href: /locations/us-sea
      pureport_connection_peering_type: PUBLIC
      pureport_connection_billing_term: HOURLY
      pureport_connection_cloud_service_hrefs:
        - /cloudServices/aws-s3-us-west-2
    - role: google
      gcp_region: us-west2  # e.g us-west-2
      gcp_network_name: ansible-network
      gcp_router_name: ansible-router
      gcp_interconnect_attachment_name: ansible-interconnect-attachment
      pureport_connection_name: My Google Cloud Connection
      pureport_connection_location_href: /locations/us-sea
      pureport_connection_speed: 50
      pureport_connection_high_availability: true
      pureport_connection_billing_term: HOURLY
    - role: vpn
      pureport_connection_name: My VPN Connection
      pureport_connection_speed: 50
      pureport_connection_high_availability: true
      pureport_connection_location_href: /locations/us-dal
      pureport_connection_billing_term: HOURLY
      pureport_connection_primary_router_ip: 192.167.1.1
      pureport_connection_secondary_router_ip: 192.167.1.2
      pureport_connection_customer_asn: 123
