---
- hosts: localhost
  tasks:
    # https://docs.ansible.com/ansible/latest/modules/gcp_compute_network_module.html
    - name: Create a Google Cloud Network
      gcp_compute_network:
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        project: "{{ gcp_project }}"
        name: "{{ gcp_network_prefix }}-network"
      register: gcp_network

    # https://docs.ansible.com/ansible/latest/modules/gcp_compute_router_module.html
    - name: Create a Google Cloud Router (1)
      gcp_compute_router:
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        project: "{{ gcp_project }}"
        name: "{{ gcp_network_prefix }}-router-1"
        region: "{{ gcp_region }}"
        bgp:
          asn: 16550  # Must be 16550
        network: "{{ gcp_network }}"
      register: gcp_router_1

    - name: Create a Google Cloud Router (2)
      gcp_compute_router:
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        project: "{{ gcp_project }}"
        name: "{{ gcp_network_prefix }}-router-2"
        region: "{{ gcp_region }}"
        bgp:
          asn: 16550  # Must be 16550
        network: "{{ gcp_network }}"
      register: gcp_router_2
      when: pureport_connection_high_availability | default(false)

    # https://docs.ansible.com/ansible/devel/modules/gcp_compute_interconnect_attachment_module.html
    - name: Create Google Cloud Interconnect Attachment (1)
      gcp_compute_interconnect_attachment:
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        project: "{{ gcp_project }}"
        name: "{{ gcp_network_prefix }}-interconnect-attachment-1"
        region: "{{ gcp_region }}"
        type: PARTNER
        edge_availability_domain: AVAILABILITY_DOMAIN_1
        router: "{{ gcp_router_1 }}"
      register: gcp_interconnect_attachment_1

    - name: Create Google Cloud Interconnect Attachment (2)
      gcp_compute_interconnect_attachment:
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        project: "{{ gcp_project }}"
        name: "{{ gcp_network_prefix }}-interconnect-attachment-2"
        region: "{{ gcp_region }}"
        type: PARTNER
        edge_availability_domain: AVAILABILITY_DOMAIN_2
        router: "{{ gcp_router_2 }}"
      register: gcp_interconnect_attachment_2
      when: pureport_connection_high_availability | default(false)

    - name: Create Pureport Network
      pureport_network:
        api_base_url: "{{ pureport_api_base_url | default(omit) }}"
        api_key: "{{ pureport_api_key }}"
        api_secret: "{{ pureport_api_secret }}"
        account_href: "{{ pureport_account_href }}"
        id: "{{ pureport_network_id | default(omit) }}"
        name: "{{ pureport_network_name }}"
      register: pureport_network

    - name: Create Pureport Google Cloud Interconnect Connection
      pureport_google_cloud_interconnect_connection:
        api_base_url: "{{ pureport_api_base_url | default(omit) }}"
        api_key: "{{ pureport_api_key }}"
        api_secret: "{{ pureport_api_secret }}"
        network_href: "{{ pureport_network.network.href }}"
        id: "{{ pureport_connection_id | default(omit) }}"
        name: "{{ pureport_connection_name }}"
        speed: "{{ pureport_connection_speed }}"
        high_availability: "{{ pureport_connection_high_availability | default(omit) }}"
        location_href: "{{ pureport_connection_location_href }}"
        billing_term: "{{ pureport_connection_billing_term }}"
        primary_pairing_key: "{{ gcp_interconnect_attachment_1.pairingKey }}"
        secondary_pairing_key: "{{ gcp_interconnect_attachment_2.pairingKey | default(omit) }}"
        wait_for_server: true
      register: pureport_connection
