---
- name: Create Google VPC Firewall Rules
  gcp_compute_firewall:
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_service_account_file }}"
    project: "{{ gcp_project }}"
    name: "{{ item.name }}"
    allowed: "{{ item.allowed }}"
    source_ranges: "{{ item.source_ranges | default(omit) }}"
    network: "{{ gcp_network }}"
  loop: "{{ gcp_vpc_firewall_rules }}"

- name: Create a Google Cloud Disk
  gcp_compute_disk:
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_service_account_file }}"
    project: "{{ gcp_project }}"
    zone: "{{ gcp_zone }}"
    name: "{{ gcp_disk_name }}"
    size_gb: "{{ gcp_disk_size_gb }}"
    source_image: "{{ gcp_disk_source_image }}"
  register: gcp_disk

- name: Create a Google Cloud Public IP Address
  gcp_compute_address:
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_service_account_file }}"
    project: "{{ gcp_project }}"
    region: "{{ gcp_region }}"
    name: "{{ gcp_public_address_name }}"
  register: gcp_address

- name: Create a Google Cloud VM
  gcp_compute_instance:
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_service_account_file }}"
    project: "{{ gcp_project }}"
    zone: "{{ gcp_zone }}"
    name: "{{ gcp_instance_name }}"
    machine_type: "{{ gcp_machine_type }}"
    disks:
      - auto_delete: true
        boot: true
        source: "{{ gcp_disk }}"
    network_interfaces:
      - network: "{{ gcp_network }}"
        access_configs:
          - name: 'External NAT'
            nat_ip: "{{ gcp_address }}"
            type: 'ONE_TO_ONE_NAT'
    metadata:
      ssh-keys: "{{ gcp_ssh_keys }}"
  register: gcp_instance
