---
- hosts: localhost
  vars:
    ansible_python_interpreter: "./venv/bin/python"  # Required for virtualenv...
  collections:
    - pureport.pureport_ansible_modules
  tasks:
    - name: Create Google Cloud Interconnect Connection
      include_role:
        name: pureport_google_cloud_interconnect
      vars:
        gcp_region: us-west2  # e.g us-west-2
        gcp_network_name: ansible-network
        gcp_router_name: ansible-router
        gcp_interconnect_attachment_name: ansible-interconnect-attachment
        pureport_connection_name: My Google Cloud Connection
        pureport_connection_location_href: /locations/us-sea
        pureport_connection_speed: 50
        pureport_connection_high_availability: true
        pureport_connection_billing_term: HOURLY
