---
- hosts: localhost
  vars:
    ansible_python_interpreter: "./venv/bin/python"  # Required for virtualenv...
  collections:
    - pureport.pureport_ansible_modules
  tasks:
    - name: Create Azure Express Route Connection (Public)
      include_role:
        name: pureport_azure_express_route
      vars:
        azure_location: westus2
        azure_express_route_circuit_name: ansibleExpressRouteCircuit
        azure_express_route_circuit_peering_location: Seattle
        azure_route_filter_name: ansibleRouteFilter
        azure_route_filter_rule_name: ansibleRouteFilterRule
        azure_route_filter_rule_service_communities:
          - 12076:53026  # Azure SQL West US 2
        pureport_connection_name: My Azure Public Connection
        pureport_connection_location_href: /locations/us-sea
        pureport_connection_high_availability: true
        pureport_connection_speed: 50
        pureport_connection_peering_type: PUBLIC
        pureport_connection_billing_term: HOURLY
