- name: Create Pureport Network
  pureport_network:
    api_base_url: "{{ pureport_api_base_url | default(omit) }}"
    api_key: "{{ pureport_api_key }}"
    api_secret: "{{ pureport_api_secret }}"
    account_href: "{{ pureport_account_href }}"
    name: "{{ pureport_network_name }}"
  register: pureport_network

- name: Create Pureport VPN Connection
  pureport_site_ipsec_vpn_connection:
    api_base_url: "{{ pureport_api_base_url | default(omit) }}"
    api_key: "{{ pureport_api_key }}"
    api_secret: "{{ pureport_api_secret }}"
    network_href: "{{ pureport_network.href }}"
    name: "{{pureport_connection_name }}"
    speed: "{{pureport_connection_speed }}"
    high_availability: "{{pureport_connection_high_availability | default(omit) }}"
    location_href: "{{pureport_connection_location_href }}"
    billing_term: "{{pureport_connection_billing_term }}"
    primary_customer_router_ip: "{{pureport_connection_primary_router_ip }}"
    secondary_customer_router_ip: "{{pureport_connection_secondary_router_ip | default(omit) }}"
    routing_type: ROUTE_BASED_BGP
    customer_asn: "{{pureport_connection_customer_asn }}"
    ike_version: V2
    ike_encryption: AES_128
    ike_integrity: SHA256_HMAC
    ike_dh_group: MODP_2048
    esp_encryption: AES_128
    esp_integrity: SHA256_HMAC
    esp_dh_group: MODP_2048
    wait_for_server: true  # Wait for the server to finish provisioning the connection
  register: pureport_connection
