---
name: tests
on:
  push:
    branches: [ master, develop, release/*, hotfix/* ]
  pull_request:
    branches: [ master, develop, release/*, hotfix/* ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/pureport

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          pip install ansible

      - name: Run tox
        working-directory: ./ansible_collections/pureport
        run: |
          tox

      - name: Run fabric ansible-test sanity
        if: "!contains(matrix.python-version, '3.8')"  # https://github.com/ansible/ansible/issues/67118
        working-directory: ./ansible_collections/pureport/fabric
        run: |
          ansible-test sanity --docker -v --color --python ${{ matrix.python-version }}
